version: 2
jobs:
  build:
    working_directory: ~/cci-demo-phoenix
    docker:
      - image: elixir:1.5.2
    steps:
      - checkout
      - run:
        name: Hex it up
        command: mix local.hex --force
      - run:
        name: Install rebar
        command: mix local.rebar
      - run:
        name: Get dependencies
        command: mix deps.get
      - run:
        name: Run tests
        command: mix test
