version: 2
jobs:
  build:
    working_directory: ~/stats_agg
    docker:
      - image: ciroque/phoenix-apps-build
    steps:
      - checkout
      - run:
        name: Hex it up
        command: mix local.hex --force
      - run:
        name: Install rebar
        command: mix local.rebar
      - run:
        name: Get dependencies
        command: mix deps.get
      - run:
        name: Run tests
        command: mix test
